# Generated by Django 3.2.14 on 2022-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_roomjoin_join_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomjoin',
            name='join_user',
            field=models.IntegerField(default=0),
        ),
    ]
