# Generated by Django 3.2.14 on 2022-09-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_roomjoin_join_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomjoin',
            name='join_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
