# Generated by Django 4.0.6 on 2022-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_img_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
